#! /usr/bin/env python
# encoding: utf-8
# mittorn, 2018

from waflib import Logs
import os

top = '.'

def options(opt):
	grp = opt.add_option_group('ref_gl options')

	grp.add_option('--enable-static-gl', action='store_true', dest='GL_STATIC', default=False,
		help = 'enable direct linking to opengl [default: %(default)s]')

	# stub
	return

def configure(conf):
	conf.env.GL_STATIC = conf.options.GL_STATIC
	if conf.env.GL_STATIC:
		conf.check(lib='GL')

	if conf.env.DEST_OS2 == 'android':
		conf.check_cc(lib='log')

def build(bld):
	libs = [ 'engine_includes', 'werror' ]
	# on PSVita do not link any libraries that are already in the main executable, but add the includes target
	if bld.env.DEST_OS == 'psvita':
		libs += [ 'sdk_includes', 'vgl_shim' ]
	else:
		libs += [ 'public', 'M' ]

	source = bld.path.ant_glob(['*.c', 'gl2_shim/*.c'])
	includes = '.'

	if bld.env.GL:
		bld.shlib(source = source,
			target = 'ref_gl',
			includes = includes,
			use = libs + (['GL'] if bld.env.GL_STATIC else []),
			defines = (['XASH_GL_STATIC=1'] if bld.env.GL_STATIC else []) + ['REF_DLL=1'],
			install_path = bld.env.LIBDIR)
